### PR TITLE
Update civisualize.civix.php

### PR DESCRIPTION
**Pull request by wintermoor**
Deprecated: Array and string offset access syntax with curly braces is deprecated

### CODE REVIEW

**Review by tttp — APPROVED** [review]
Hey @wintermoor, it seems that your forks has a lot of changes and improvements over here, 

are they things you could share back?

**Comment by wintermoor** [comment]
Sorry, am new to Github. There was only one change in the civic.php

**Comment by tttp** [comment]
Yeah all good, that was just me looking at your repository ;)

**Comment by wintermoor** [comment]
This fix won't help! Civix will generate a new civix.php with this minor "bug". 
We have to take a deeper look at https://github.com/totten/civix

**Pull request merged**
